#ifndef _enumBHVErrorCodes_HG_
#define _enumBHVErrorCodes_HG_

namespace BVHErrorCodes
{
	enum enumBVHErrorCodes
	{
		OK,
		CANT_FIND_OR_OPEN_FILE,
		// HIEARCHY portion
		EXPECTED_HIERARCHY_BUT_GOT_UNKNOWN,
		EXPECTED_ROOT_BUT_GOT_UNKNOWN,
		EXPECTED_OPEN_CURLY_BRACKET,
		EXPECTED_CLOSED_CURLY_BRACKET,
		EXPECTED_OFFSET,
		EXPECTED_CHANNELS,
		EXPECTED_JOINT_OR_EndSite,
		EXPECTED_End_Site,
		// Motion portion
		EXPECTED_FRAMES_BUT_GOT_SOMETHING_ELSE,
		EXPECTED_FRAME_BUT_GOT_SOMETHING_ELSE,
		EXPECTED_TIME_BUT_GOT_SOMETHING_ELSE,
		//
		CAN_NOT_INDEX_THE_CHANNEL_DATA,
		//
		GENERAL_OR_UNKNOWN_ERROR
	};
}

#endif